apiVersion: v1
kind: Service
metadata:
  name: frontends
spec:
  selector:
    app: frontends
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontends
spec:
  selector:
    matchLabels:
      app: frontends
  replicas: 1
  # strategy:
  #   type: RollingUpdate
  #   rollingUpdate:
  #     maxUnavailable: 50%
  #     maxSurge: 50%
  template:
    metadata:
      labels:
        app: frontends
    spec:
      containers:
        - name: frontend
          image: 19880402/frontend:imed
          # image: crudappcontainerregistry.azurecr.io/frontend:production
          ports:
            - containerPort: 3000
          imagePullPolicy: Always
